### ISSUE TITLE
monsters don't appear after second puzzle

### ISSUE THREAD

**Issue by aluminumbulb** [Alone-Not-Lonely/alone-not-lonely#21]

**Comment by aluminumbulb** [comment]
They do only if blocked by some object in an earlier puzzle

**Comment by aluminumbulb** [comment]
Again, not fixed yet, but for some reason removing the rigidbody from the portal caused that monster path to begin behaving properly. Root cause still unknown.

**Comment by rbaua** [comment]
Issue was with portals being too low, monster started clipping into the ground, colliding with it, registering as stuck, and then turning around
