### ISSUE TITLE
Players can't put down boxes

### ISSUE THREAD

**Issue by rbaua** [Alone-Not-Lonely/alone-not-lonely#22]
Specifically the second hallway box, but may be problem with more than just that one

**Comment by rbaua** [comment]
dayna + mia reported that while this issue was happening, both UI prompts were present

**Comment by aluminumbulb** [comment]
I'm not going to call this closed yet, but I may have fixed it. I think the player's collider was capturing multiple parts of the chair and the box. I changed the player's anxiety trigger to not interfere with the process, as well as making the chair one object.

**Comment by rbaua** [comment]
I'm going to call this closed until the bug reemerges, since it hasn't been seen for several days now
