### ISSUE TITLE
Camera bob + wider FOV

### ISSUE THREAD

**Issue by rbaua** [Alone-Not-Lonely/alone-not-lonely#30]

**Comment by aluminumbulb** [comment]
I shrunk FOV to 80, not a big change but worth noting.

A basic headbob script is in there, now functioning. It takes some responsibility off of camera controller, which I'd like to avoid from an organizational point of view, so I'll get to merging them or distributing the load of control between them (maybe one for rotation and another for position?).

**Comment by aluminumbulb** [comment]
Formally consolidated and good to go
