### ISSUE TITLE
Mouse not staying locked and invisible

### ISSUE THREAD

**Issue by aluminumbulb** [Alone-Not-Lonely/alone-not-lonely#6]
After implementing the new input manager system, the mouse no longer re-locks after becoming unpaused. Tests indicate that it is locked at the end of the  "unpause" function. I can't seem to find what else may be freeing it.

**Comment by rbaua** [comment]
According to this unity forums post, the cursor lockstate behaves differently in engine versus in the build: https://forum.unity.com/threads/cursor-lockstate-cursorlockmode-locked-not-working-at-all.520192/
Tested in the build and it works as expected
